### ISSUE TITLE
Allow per-rule ignores

### ISSUE THREAD

**Issue by queengooborg** [OnkarRuikar/markdownlint-rule-search-replace#109]
When applying the formatting rules of mdn/content to mdn/translated-content, we ran into a slight issue regarding smart (curly) quotes with the Chinese locale.  Apparently, it is [grammatically accurate to use smart quotes in place of normal quotes](https://github.com/mdn/translated-content/pull/14222#issuecomment-1636569122), so the rule to search and replace smart quotes causes localization issues.

It would be great to see a `filter` option added, which is an object containing optional `include` and `exclude` properties, which are either a string or array of strings containing file globs for that rule to apply to or ignore.  For example:

```json
{
  "name": "curly-double-quotes",
  "message": "Don't use curly double quotes",
  "searchPattern": "/“|”/g",
  "replace": "\"",
  "searchScope": "text",
  "filter": {"exclude": "**/zh-cn/**"} // Ignore all Simplified Chinese files
},
{
  "name": "m-dash",
  "message": "Don't use '--'. Use m-dash — instead",
  "search": " -- ",
  "replace": " — ",
  "searchScope": "text",
  "filter": {"exclude": ["README.md", "**/es/**"]} // Ignore README.md in root, and all Spanish files
},
{
  "name": "em-dash",
  "message": "Don't use '--'. Use em-dash — instead",
  "search": " -- ",
  "replace": " — ",
  "searchScope": "text",
  "filter": {"include": "**/es/**"} // Only apply to Spanish files
},
```

**Comment by OnkarRuikar** [comment]
- This was fixed using an existing mechanism in https://github.com/mdn/translated-content/pull/15106

**Comment by queengooborg** [comment]
I don't really consider this to be fixed, only mitigated.  I'm going to work on implementing this functionality in a fork.

**Comment by OnkarRuikar** [comment]
> I don't really consider this to be fixed, only mitigated. I'm going to work on implementing this functionality in a fork.

Adding third mechanism to filter files will complicate things. For example, which mechanism should take precedence and how will they interplay?

This could've been solved using separate command for each locale as well:
```json
"lint:md" : "lint-zh-cn:md; lint-es:md; lint-ru:md ...",
"lint-zh-cn:md": "markdownlint-cli2 --config zh-cn.markdonwlint.config docs/zh-cn/*.md files/zh-cn/**/*.md"
"lint-es:md": "markdownlint-cli2 --config es.markdonwlint.config docs/es/*.md files/es/**/*.md"
```
